/* Készítő: H.Tibor */

// loadGoogleMaps({"ID":"","lati":"","longi":"","cimke":"","irsz":"","varos":"","utca":"","tel":"","fax":"","email":"","web":""});
function loadGoogleMaps(data) {
	var src = '<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-2" /><script src="http://maps.google.com/maps/api/js?sensor=false"></'+'script><style>html,body{width:100%;height:100%;margin:0px;padding:0px;}</style></head><body><div id="'+data["ID"]+'" class="gmaps" style="height:100%;width:100%;"></div><script>'
	// var src = '<script src="http://maps.google.com/maps/api/js?sensor=false"></'+'script><style>html,body{width:100%;height:100%;margin:0px;padding:0px;}</style><div id="'+data["ID"]+'" class="gmaps" style="height:100%;width:100%;"></div><script>'
	+'var data = {"ID":"'+data["ID"]+'","lati":"'+data["lati"]+'","longi":"'+data["longi"]+'","cimke":"'+data["cimke"]+'","irsz":"'+data["irsz"]+'","varos":"'+data["varos"]+'","utca":"'+data["utca"]+'","tel":"'+data["tel"]+'","fax":"'+data["fax"]+'","email":"'+data["email"]+'","web":"'+data["web"]+'"};'
	+'var gMap'+data["ID"]+' = geoCode'+data["ID"]+' = gMapMarker'+data["ID"]+' = "";'
	+'geoCode'+data["ID"]+' = new google.maps.Geocoder();'
	+'var gMapLatLng = new google.maps.LatLng(parseFloat(data["lati"]), parseFloat(data["longi"]));'
	+'var gMapDefPozLoad = { zoom : 15, center : gMapLatLng, mapTypeControlOptions:{ mapTypeIds : [], style : google.maps.MapTypeControlStyle.DEFAULT }, mapTypeId : google.maps.MapTypeId.ROADMAP };'
	+'gMap'+data["ID"]+' = new google.maps.Map(document.getElementById(data["ID"]), gMapDefPozLoad);'
	+'gMapMarker'+data["ID"]+' = new google.maps.Marker({'
	+'		position : gMapLatLng,'
	+'		map : gMap'+data["ID"]+','
	+'		draggable : false'
	+'	});'
	+''
	+'var InfoTextOut  = "";'
	+'if(data["cimke"]) {'
	+'		InfoTextOut += "<p style=\'font-size:14px;color:#555;\'><b>"+(data["cimke"])+"</b></p>";'
	+'}'
	+'if(data["irsz"] || data["varos"] || data["utca"]) {'
	+'		InfoTextOut += "<p style=\'font-size:12px;color:#555;\'>";'
	+'		InfoTextOut += "<b>Cím:</b> ";'
	+'		InfoTextOut += (data["irsz"])+" ";'
	+'		InfoTextOut += (data["varos"]);'
	+'		InfoTextOut += ((data["varos"] && data["utca"])?(", "):(""));'
	+'		InfoTextOut += (data["utca"]);'
	+'		InfoTextOut += "</p>";'
	+'}'
	+'if(data["tel"] || data["fax"]) {'
	+'		InfoTextOut += "<p style=\'font-size:12px;color:#555;\'>";'
	+'		InfoTextOut += ((data["tel"])?("<b>Tel:</b> "+(data["tel"])):(""));'
	+'		InfoTextOut += ((data["tel"] && data["fax"])?(", "):(""));'
	+'		InfoTextOut += ((data["fax"])?("<b>Fax:</b> "+(data["fax"])):(""));'
	+'		InfoTextOut += "</p>";'
	+'}'
	+'if(data["email"] || data["web"]) {'
	+'		InfoTextOut += "<p style=\'font-size:12px;color:#555;\'>";'
	+'		InfoTextOut += ((data["email"])?("<b>Email:</b> <a href=\'mailto:"+(data["email"])+"\'>"+(data["email"])+"</a>"):(""));'
	+'		InfoTextOut += ((data["email"] && data["web"])?(", "):(""));'
	+'		InfoTextOut += ((data["web"])?("<b>web:</b> <a href=\'http://"+(data["web"])+"/\' target=\'_blank\'>"+(data["web"])+"</a>"):(""));'
	+'		InfoTextOut += "</p>";'
	+'}'
	+''
	+'var contentString'+data["ID"]+' = "<div id=\'"+data["ID"]+"InfoText\'>"+InfoTextOut+"</div>";'
	+'var infowindow'+data["ID"]+' = new google.maps.InfoWindow({ content: contentString'+data["ID"]+' });'
	+''
	+'setTimeout(function() {'
	+'	infowindow'+data["ID"]+'.open(gMap'+data["ID"]+',gMapMarker'+data["ID"]+');'
	+'},100);'
	+'</'+'script>'
	+'</body></html>';
	
	$('#'+data["ID"]).append('<iframe id="frame'+data["ID"]+'" style="margin:0px;padding:0px;width:100%;height:100%;overflow:hidden;"></iframe>');
	document.getElementById('frame'+data["ID"]).contentWindow.document.write(src);
	document.getElementById('frame'+data["ID"]).contentWindow.document.close();
}